#!/usr/local/bin/php
<?php
    //loading composer's autoload
    chdir(__DIR__);
    if (file_exists('vendor/autoload.php')) {
        include 'vendor/autoload.php';
    }

    use Assetic\Asset\AssetCollection;
    use Assetic\Factory\AssetFactory;
    use Assetic\Asset\FileAsset;
    use Assetic\Asset\GlobAsset;
    use Assetic\Filter\LessFilter;
    use Assetic\Filter\CssMinFilter;
    use Assetic\Filter\JSMinFilter;
    use Assetic\AssetWriter;
    use Assetic\AssetManager;

    //Asset manager
    $am = new AssetManager();

    //Add all css files
    $css = new AssetCollection(array(
        new FileAsset('vendor/twbs/bootstrap/less/bootstrap.less', array( new LessFilter(), new CssMinFilter() ) ),
        new GlobAsset('assets/less/*.less', array( new LessFilter(), new CssMinFilter() ) ),
    ));
    $css->setTargetPath('style.min.css');
    $am->set('stylecss', $css);

    $js = new AssetCollection(array(
        new FileAsset('components/jquery/jquery.js', array( new JSMinFilter() ) ),
        new FileAsset('vendor/twbs/bootstrap/js/affix.js', array( new JSMinFilter() ) ),
        new FileAsset('vendor/twbs/bootstrap/js/button.js', array( new JSMinFilter() ) ),
        new FileAsset('vendor/twbs/bootstrap/js/scrollspy.js', array( new JSMinFilter() ) ),
        new FileAsset('assets/js/app.js', array( new JSMinFilter() ) ),
    ));
    $js->setTargetPath('app.min.js');
    $am->set('javascript', $js);


    // Dumping assets into public
    $writer = new AssetWriter('web');
    $writer->writeManagerAssets($am);